# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e6f6501733cabb6b125158d2572505f3"
name = "post-purchase-app"
application_url = "https://08xc581w-3000.inc1.devtunnels.ms"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_metaobject_definitions,write_metaobjects,write_order_edits,write_products"

[auth]
redirect_urls = [ "https://08xc581w-3000.inc1.devtunnels.ms/api/auth" ]

[shop.metafields.app.app_url]
type = "single_line_text_field"
name = "App Backend URL"
description = "The backend URL used by the checkout extension to communicate with the app"

  [shop.metafields.app.app_url.access]
  admin = "merchant_read"
